### ISSUE TITLE
Delay Respond from LEDs

### ISSUE THREAD

**Issue by Majda995** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#34]
I am using the LED WS2812b to play MIDI files that i import into the code. it works but i have a big timing delay between the MIDI-File and the playing LEDs do not match each other. can someone please help me?

**Comment by dhalbert** [comment]
Have you tried the regular `neopixel` library? Are you using this library to solve another problem? Which board is it?

**Comment by Majda995** [comment]
i used the standard neopixel library (with PWM signal) and right now i am using noepixel_spi. i am using raspberry pi 3

**Comment by dhalbert** [comment]
I don't think the problem here is inherent to the library. It may be partly due to Linux not being a real-time OS, and perhaps partly due to how your program works. For those reasons I believe this is more a library use question than a library bug. We can give you better support in https://forums.adafruit.com/viewforum.php?f=60 for that. Could you start a thread ther insteade, state the problem, mention the RPi 3, the versions of software you are using (OS and libraries), and post your program as well?

**Comment by Majda995** [comment]
will do that thanks :)
